---
name: xhook_int-load_acct_dbg_logs
summary: Load account debug logs
description: Load account debug logs
uri: https://github.com/esDataCo/tree/master/co-test
publish: private

triggers:
  daily_run:
    scheduled: true
    trigger: system-cron
    parameters:
      schedule: '0 0 * * *'

parameters:
  environment: hooks-testnet-v2.xrpl-labs.com

steps:
  acctrc_to_db_01:
    step: xhook_int-acctrc_to_db
